[package]
name = "woods-client"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_spicy_networking = "0.5.0"
woods-common = { path = "../common" }
simple_logger = { version = "1.13.0" }
log = "0.4"